version: "3.8"
services:
  web:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - front

  front:
    image: node:14-alpine
    ports:
      - 3000:3000
    volumes:
      - ./front:/code
    working_dir: /code
    command: npm start
    depends_on:
      - backend
  backend:
    image: node:14-alpine
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./backend:/code
    working_dir: /code
    command: npm start
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    env_file:
      - ./mysql.env
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
